[package]
name = "distribution-meta"
version = "1.0.0"
edition = "2018"
publish = false

[dependencies.distribution]
path = ".."

[dependencies.elrond-wasm]
version = "0.23.1"

[dependencies.elrond-wasm-debug]
version = "0.23.1"
